import 'dart:convert';
import 'dart:io';

import 'package:qirad_core/qirad_core.dart';
import 'package:test/test.dart';

/// PHP -> Dart. The fixture is a real sync response captured by the relay's
/// SharedFixturesTest (where the manager uploads two versions of seq 5). It is
/// generated by PHP, not by hand. This test only reads it, through receiveText.
void main() {
  test('a relay response with two versions of seq 5 flags the manager', () async {
    final fixture =
        jsonDecode(
              await File(
                '../../testdata/relay_equivocation_sync.json',
              ).readAsString(),
            )
            as Map<String, dynamic>;
    final response = fixture['response'] as Map<String, dynamic>;
    final records = (response['records'] as List).cast<String>();
    final conflicts = (response['conflicts'] as List).cast<String>();

    String typeOf(String text) =>
        (jsonDecode(text) as Map<String, dynamic>)['type'] as String;
    String authorOf(String text) =>
        (jsonDecode(text) as Map<String, dynamic>)['author'] as String;

    final validator = Validator();

    // The partnership_create must be accepted first, so the parties are known.
    // The response may list the other records in any order.
    final create = records.singleWhere(
      (text) => typeOf(text) == 'partnership_create',
    );
    expect(await validator.receiveText(create), ReceiveOutcome.accepted);
    final investorKey = authorOf(create);
    for (final text in records) {
      if (text != create) await validator.receiveText(text);
    }

    // The stored version is already known (duplicate). The second version is the clash.
    final manager = authorOf(conflicts.first);
    expect(manager, isNot(investorKey));
    final outcomes = [
      for (final text in conflicts) await validator.receiveText(text),
    ];
    expect(outcomes, [
      ReceiveOutcome.duplicateIgnored,
      ReceiveOutcome.equivocating,
    ]);

    expect(validator.equivocatingFromSeq, {manager: 5});
  });
}
